# Test configuration for service validation
# This uses a fake token - the service will fail gracefully
bot:
  name: "test-bot"
  description: "Test bot for service validation"
  
discord:
  token: "fake-token-for-testing"
  command_prefix: "!test"
  
ollama:
  base_url: "http://127.0.0.1:11434"
  model: "llama3"
  timeout: 60
  
system_prompt: |
  Test bot for service validation. Modified to test auto-restart!
  
storage:
  enabled: false
  
message:
  max_length: 1900
  typing_indicator: true
  
rate_limit:
  enabled: false
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"